services:
  prometheus:
    image: prom/prometheus:v2.51.0
    restart: unless-stopped
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.8
    restart: unless-stopped
    command:
      - "-config.file=/etc/loki/loki.yml"
    volumes:
      - ./configs/loki.yml:/etc/loki/loki.yml
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.0.0
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.27.0
    restart: unless-stopped
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    volumes:
      - ./configs/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitoring


# Якщо треба моніторити і контроль ноду

#  alloy:
#    image: grafana/alloy:v1.14.0
#    container_name: grafana-alloy
#    restart: unless-stopped
#    volumes:
#      - ../configs/config.alloy:/etc/alloy/config.alloy
#    command:
#      - "run"
#      - "/etc/alloy/config.alloy"
#    ports:
#      - "12345:12345"
#    networks:
#      - monitoring

volumes:
  prometheus-data:
  loki-data:
  grafana-data:

networks:
  monitoring:
