[monitoring_node]
monitoring_node_main1 ansible_host=157.180.35.146 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519_uapp

# exapmle
# monitoring_node_example ansible _host=example_ip ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519_uapp

[monitored_servers]
server1 ansible_host=IP
server2 ansible_host=IP